### PR TITLE
fix phone number and description validators

### LINKED ISSUE #161: Form validators need to be fixed
### Description - What happened? *

With version 2.1.2 we observed a new bug, that has to do with required input fileds. Sometimes the user is asked to input information eventhough the info is already entered. This occures when data is inserted by copy and paste. The Registration Process as well as the profil pages are affected by this. I attached one screenshot from the registration process where the input is not recognized due to a trailing space. The scond screenshot shows part of the organizations profile. I removed trailing spaces but unfortunatelly can't pinpoint why the input is not recognized.

### Expected Behavior *

?

### Observed Behavior *

?

### Steps to Reproduce

_No response_

### Context Information

_No response_

### Relevant log output

_No response_

### Screenshots

1.
required_field_input_user_registration

2.
required_field_input_organization_menu

### PR DESCRIPTION
**Pull request by illfixit**
_What issues does this PR close?_
closes #161 Form validators need to be fixed

```[tasklist]
### Checklist
- [x] The PR title is short and expressive.
- [x] I have updated the CHANGELOG.md. See [changelog_update.md](https://github.com/sovity/authority-portal/tree/main/docs/dev/changelog_updates.md) for more information.
- [ ] I have updated the Deployment Migration Notes Section in the CHANGELOG.md for any configuration / external API changes.
- [x] I have performed a **self-review**
```

### CODE REVIEW

**Comment by kamilczaja** [comment]
Now that we allow spaces at the end of the phone number, wouldn't it make sense to strip them on submit? Either in FE before sending it to the BE or in the BE itself before persisting it in a database.

I can't imagine persisting potentially 15 whitespaces at the end of the string would be great - imagine how'd that look when displayed in FE @illfixit

**Comment by illfixit** [comment]
> Now that we allow spaces at the end of the phone number, wouldn't it make sense to strip them on submit? Either in FE before sending it to the BE or in the BE itself before persisting it in a database.
> 
> I can't imagine persisting potentially 15 whitespaces at the end of the string would be great - imagine how'd that look when displayed in FE @illfixit

I'm not sure anyone will add 15 whitespaces even if they copy paste but I'd imagine it to be made best in one place in backend because otherwise it's 10 places in FE and imo BE solution is more consistent

**Review by kamilczaja — COMMENTED** [review]
FE LGTM

**Review by jridderbusch — APPROVED** [review]
LGTM

**Pull request merged**
